[versions]
lombok = "1.18.38"
junit = "5.13.3"
slf4j = "2.0.17"
commons-text = "1.10.0"
commons-lang3 = "3.13.0"
postgresql = "42.7.7"
liquibase = "4.33.0"
spring-boot = "3.5.3"
spring-dependency-management = "1.1.7"
mapstruct = "1.6.3"
swagger-annotations = "2.2.34"
springdoc = "2.8.9"
h2 = "2.2.220"
jetbrains-annotations = "24.1.0"

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }

[libraries]
# Lombok
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

# JUnit
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

# SLF4J
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

# Apache
commons-text = { module = "org.apache.commons:commons-text", version.ref = "commons-text" }
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang3" }

# PostgreSQL Driver
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }

# Liquibase
liquibase = { module = "org.liquibase:liquibase-core", version.ref = "liquibase" }

# Spring Boot
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter", version.ref = "spring-boot" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "spring-boot" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "spring-boot" }

# Spring Boot Test
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "spring-boot" }

# Spring Dependency Management Plugin
spring-dependency-management = { module = "io.spring.gradle:dependency-management-plugin", version.ref = "spring-dependency-management" }

# MapStruct Core Dependency
mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstruct" }

# MapStruct Annotation Processor for Generating Mappers
mapstruct-processor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstruct" }

# Swagger Core Annotations
swagger-annotations = { module = "io.swagger.core.v3:swagger-annotations", version.ref = "swagger-annotations" }

# SpringDoc OpenAPI for Spring Boot
springdoc-openapi-starter-webmvc-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }

# H2
h2 = { module = "com.h2database:h2", version.ref = "h2" }

# JetBrains
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
